#!/bin/bash
# selenium - this script starts and stops the selenium grid
#
# chkconfig:   - 85 15
# description: Selenium Grid is a distributed testing platform for browser-based automation.
# processname: selenium
# pidfile:     /var/log/selenium-server/selenium.pid

# Source function library.
. /etc/rc.d/init.d/functions
selenium_dir=/opt/selenium-server
log_dir=/var/log/selenium-server
error_log=$log_dir/selenium_error.log
std_log=$log_dir/selenium_std.log
pid_file=$log_dir/selenium.pid
java=/bin/java
selenium="$selenium_dir/selenium-server-standalone-2.53.0.jar"
user=screener

start() {
    if test -f $pid_file
    then
        PID=`cat $pid_file`
        if  ps --pid $PID >/dev/null;
            then
                echo "Selenium is already running: $PID"
                exit 0
            else
                echo "Removing stale pid file: $pid_file"
        fi
    fi

    echo -n "Starting Selenium..."
    su $user -c "$java -jar $selenium -host 127.0.0.1 >$std_log 2>$error_log &"

    if [ $? == "0" ]; then
        success
    else
        failure
    fi
    echo
    ps  -C java -o pid,cmd | grep $selenium  | awk {'print $1 '} > $pid_file
}

stop() {
    if test -f $pid_file
    then
        echo -n "Stopping Selenium..."
        PID=`cat $pid_file`
        su $user -c "kill -3 $PID"
        if kill -9 $PID ;
                then
                        sleep 2
                        test -f $pid_file && rm -f $pid_file
                        success
                else
                        echo "Selenium could not be stopped..."
                        failure
                fi
    else
            echo "Selenium is not running."
            failure
    fi
    echo
}

status() {
    if test -f $pid_file
    then
        PID=`cat $pid_file`
        if  ps --pid $PID >/dev/null ;
        then
            echo "Selenium is running...$PID"
        else
            echo "Selenium isn't running..."
        fi
    else
            echo "Selenium isn't running..."
    fi
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        stop
        start
        ;;
    status)
        $1
        ;;
    *)
        echo "Usage: $SELF start|stop|restart|status"
        exit 1
    ;;
esac
